image: archlinux
packages:
  - ca-certificates
  - cpanminus
  - git
  - just
  - openssl
  - perl-dbd-pg
  - postgresql
  - postgresql-libs
environment:
  PERL5LIB: "$HOME/grokloc-perl/lib:$HOME/grokloc-perl/local/lib/perl5"
tasks:
  - grokloc-db: |
      git clone https://git.sr.ht/~bradclawsie/grokloc-db
      pushd grokloc-db
      sudo just initdb
      sudo systemctl start postgresql.service && sleep 3
      just create-users create-databases alter-grants apply-schema
      popd
  - deps: |
      pushd grokloc-perl
      mkdir -p local
      /usr/bin/vendor_perl/cpanm -l local -n Carton
      PERL5LIB="$HOME/grokloc-perl/local/lib/perl5"; local/bin/carton install
  - tests: |
      pushd grokloc-perl
      just check critic test

