image: archlinux

tasks:
  - update-pacman: |
      sudo pacman -Sy
  - setup:
      sudo bash grokloc-perl/setup-arch.sh
  - grokloc-db: |
      git clone https://git.sr.ht/~bradclawsie/grokloc-db
      pushd grokloc-db
      sudo just initdb
      sudo systemctl start postgresql.service && sleep 3
      just create-users create-databases alter-grants apply-schema
      popd
  - tests: |
      pushd grokloc-perl
      fish -c "just deps check critic test"

